### ISSUE TITLE
[Feature Request] SSL Parameter

### ISSUE THREAD

**Issue by S3cur3Th1sSh1t** [0xn0ne/weblogicScanner#14]
Hi,

first of all great tool! This makes weblogic vulnerability testing fast.

I found some applications, which server the /wls-wsat/CoordinatorPortType Endpoint via HTTPS instead of HTTP. So SSL support would be very nice at this point.

Greetings

**Comment by 0xn0ne** [comment]
The program will automatically switch the https protocol to try again, unless it response to a request for http protocol, as described in this section.
https://github.com/0xn0ne/weblogicScanner/blob/master/utils.py#L109

**Comment by 0xn0ne** [comment]
maybe you want to force https, I'll try it.

**Comment by S3cur3Th1sSh1t** [comment]
I was looking for verify=true in ws.py only. It failed because the target was using a self signed certificate and Verify is set to true :raised_hand:
Got it working now, thanks.
