### ISSUE TITLE
可以支持https吗

### ISSUE THREAD

**Issue by uuuuuuzeus** [0xn0ne/weblogicScanner#15]
可以支持https吗

**Comment by 0xn0ne** [comment]
程序是会自动切换 https 协议的，可以参考这个部分，除非在请求 http 协议的时候出现了响应，否则会自动切换 https 协议进行再次尝试，具体可以参考这块部分：
https://github.com/0xn0ne/weblogicScanner/blob/master/utils.py#L109

**Comment by 0xn0ne** [comment]
设置了一个可以强制使用https的参数
