### ISSUE TITLE
如果有时间修改的话，还是希望脚本的检测逻辑准一些。。。

### ISSUE THREAD

**Issue by sv3nbeast** [0xn0ne/weblogicScanner#17]
<img width="941" alt="image" src="https://user-images.githubusercontent.com/55974091/183240683-3f0546ba-04e5-4284-af19-ac1f062bb1b3.png">
发现了一堆误报，打开看了一下console的检测逻辑，才看到这么离谱。。主要还是原作者写的离谱了

**Comment by 0xn0ne** [comment]
hhh，这个我知道，本来我想加爆破的，但是想想算了，python的并发能力太差了，而且特意标记了模块检测
<img width="314" alt="image" src="https://user-images.githubusercontent.com/16507416/183277576-8b91a891-f735-4bec-a104-e6b9eda8c784.png">
