### ISSUE TITLE
希望能添加颜色标注和解析http协议的目标

### ISSUE THREAD

**Issue by TajangSec** [0xn0ne/weblogicScanner#18]
我一直扫描不成功，因为我的目标是http://xx.xx.xx.xx，删掉http才行
然后希望存在漏洞的提示信息改成其他明显颜色

**Comment by 0xn0ne** [comment]
因为这个工具会扫描 `T3`、`http` 协议，如果加 `http://` 的话，针对 `T3` 协议的扫描无法识别字符串。在输入目标前，可以使用subline、vscode结合正则表达式 `https?://` 批量搜索替换掉带 `http://` 或 `https://` 的地址
