### ISSUE TITLE
-t 不能加ip列表文件

### ISSUE THREAD

**Issue by tysmlq** [0xn0ne/weblogicScanner#8]
根据说明，python -t 可以跟随ip地址或文件
但测试发现-t ip.txt（自定义ip文件）报错
ip.txt格式：
ip 7001
ip:7001
ip
上述格式均不成功

**Comment by 0xn0ne** [comment]
> 根据说明，python -t 可以跟随ip地址或文件
> 但测试发现-t ip.txt（自定义ip文件）报错
> ip.txt格式：
> ip 7001
> ip:7001
> ip
> 上述格式均不成功

能不能把ip.txt上传出来看一下？我这边运行是正常的
![image](https://user-images.githubusercontent.com/16507416/86764815-ee9c8680-c07a-11ea-8296-6a760b4d7664.png)

**Comment by tysmlq** [comment]
又测试可以了，奇怪。
