### ISSUE TITLE
this tool is great but need to be more fast 

### ISSUE THREAD

**Issue by smackerdodi** [0xn0ne/weblogicScanner#9]
this tool need to be fast so could you use asyncio or threading library to make it more fast

**Comment by 0xn0ne** [comment]
I found this problem a long time ago, and recently tried python's multi-threaded and multi-process combinations, and the whole data control process is so stupid that the tool won't use higher performance detection algorithms. I may try to use golang for future development.

**Comment by 0xn0ne** [comment]
This should be what you want https://github.com/0xn0ne/scoutHawk/releases

This program was completed six months ago, but there are still a lot of problems, and recently there is not much time to complete it, first as a temporary version

Honestly I don't think there is any point in continuing to develop it, after all there are scanners like nessus. I don't think the development will continue to be better than it.
